ALTER TABLE UAB_GET.T_CIUDAD
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.T_CIUDAD CASCADE CONSTRAINTS PURGE
/

--
-- T_CIUDAD  (Table) 
--
--   Row count:9
CREATE TABLE UAB_GET.T_CIUDAD
(
  ID_CIUDAD       NUMBER(15)                    NOT NULL,
  NOMBRE          VARCHAR2(100 BYTE),
  APP_ID_USUARIO  NUMBER(15),
  AUD_ESTADO      NUMBER(1)                     DEFAULT 1,
  AUD_USUARIO     VARCHAR2(50 BYTE)             DEFAULT USER,
  AUD_FECHA       TIMESTAMP(6)                  DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN UAB_GET.T_CIUDAD.AUD_FECHA IS 'Campo donde se almacena la fecha de registro del sistema'
/

COMMENT ON COLUMN UAB_GET.T_CIUDAD.FECHA_REGISTRO IS 'Campo donde se lamacena la fecha de la aplicacion'
/



ALTER TABLE UAB_GET.T_FACTURA
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.T_FACTURA CASCADE CONSTRAINTS PURGE
/

--
-- T_FACTURA  (Table) 
--
--   Row count:0
CREATE TABLE UAB_GET.T_FACTURA
(
  ID_FACTURA      NUMBER(15)                    NOT NULL,
  MONTO           NUMBER(15,2),
  GLOSA           VARCHAR2(500 BYTE),
  NIT             VARCHAR2(100 BYTE),
  APP_ID_USUARIO  NUMBER(15),
  AUD_ESTADO      NUMBER(1),
  AUD_USUARIO     VARCHAR2(50 BYTE),
  AUD_FECHA       DATE,
  FECHA_REGISTRO  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.T_HORARIO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.T_HORARIO CASCADE CONSTRAINTS PURGE
/

--
-- T_HORARIO  (Table) 
--
--   Row count:44
CREATE TABLE UAB_GET.T_HORARIO
(
  ID_HORARIO      NUMBER(15)                    NOT NULL,
  HORA            VARCHAR2(15 BYTE),
  APP_ID_USUARIO  NUMBER(15),
  AUD_ESTADO      NUMBER(1)                     DEFAULT 1,
  AUD_USUARIO     VARCHAR2(50 BYTE)             DEFAULT USER,
  AUD_FECHA       TIMESTAMP(6)                  DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.TPAR_ESTADO_ASIENTO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.TPAR_ESTADO_ASIENTO CASCADE CONSTRAINTS PURGE
/

--
-- TPAR_ESTADO_ASIENTO  (Table) 
--
--   Row count:3
CREATE TABLE UAB_GET.TPAR_ESTADO_ASIENTO
(
  ID_ESTADO_ASIENTO  NUMBER(15)                 NOT NULL,
  DESCRIPCION        VARCHAR2(50 BYTE),
  APP_ID_USUARIO     NUMBER(15),
  AUD_ESTADO         NUMBER(1)                  DEFAULT 1,
  AUD_USUARIO        VARCHAR2(50 BYTE)          DEFAULT USER,
  AUD_FECHA          TIMESTAMP(6)               DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO     DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.TPAR_GENERO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.TPAR_GENERO CASCADE CONSTRAINTS PURGE
/

--
-- TPAR_GENERO  (Table) 
--
--   Row count:3
CREATE TABLE UAB_GET.TPAR_GENERO
(
  ID_GENERO       NUMBER(15)                    NOT NULL,
  DESCRIPCION     VARCHAR2(50 BYTE),
  APP_ID_USUARIO  NUMBER(15),
  AUD_ESTADO      NUMBER(1)                     DEFAULT 1,
  AUD_USUARIO     VARCHAR2(50 BYTE)             DEFAULT USER,
  AUD_FECHA       TIMESTAMP(6)                  DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.TPAR_PRECIO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.TPAR_PRECIO CASCADE CONSTRAINTS PURGE
/

--
-- TPAR_PRECIO  (Table) 
--
--   Row count:17
CREATE TABLE UAB_GET.TPAR_PRECIO
(
  ID_PRECIO       NUMBER(15)                    NOT NULL,
  PRECIO          NUMBER(15,4),
  COSTO           NUMBER(15,4),
  OBSERVACIONES   VARCHAR2(500 BYTE),
  APP_ID_USUARIO  NUMBER(15),
  AUD_ESTADO      NUMBER(1)                     DEFAULT 1,
  AUD_USUARIO     VARCHAR2(50 BYTE)             DEFAULT USER,
  AUD_FECHA       TIMESTAMP(6)                  DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE UAB_GET.TPAR_PRECIO IS 'Tabla donde se almacenan los distintos precios que existen'
/



ALTER TABLE UAB_GET.TPAR_SUCURSAL
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.TPAR_SUCURSAL CASCADE CONSTRAINTS PURGE
/

--
-- TPAR_SUCURSAL  (Table) 
--
--   Row count:11
CREATE TABLE UAB_GET.TPAR_SUCURSAL
(
  ID_SUCURSAL     NUMBER(15)                    NOT NULL,
  NOMBRE          VARCHAR2(100 BYTE),
  TELEFONO        VARCHAR2(50 BYTE),
  DIRECCION       VARCHAR2(150 BYTE),
  APP_ID_USUARIO  NUMBER(15),
  AUD_ESTADO      NUMBER(1)                     DEFAULT 1,
  AUD_USUARIO     VARCHAR2(50 BYTE)             DEFAULT USER,
  AUD_FECHA       TIMESTAMP(6)                  DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.TPAR_TIPO_ASIENTO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.TPAR_TIPO_ASIENTO CASCADE CONSTRAINTS PURGE
/

--
-- TPAR_TIPO_ASIENTO  (Table) 
--
--   Row count:2
CREATE TABLE UAB_GET.TPAR_TIPO_ASIENTO
(
  ID_TIPO_ASIENTO  NUMBER(15)                   NOT NULL,
  DESCRIPCION      VARCHAR2(50 BYTE),
  APP_ID_USUARIO   NUMBER(15),
  AUD_ESTADO       NUMBER(1)                    DEFAULT 1,
  AUD_USUARIO      VARCHAR2(50 BYTE)            DEFAULT USER,
  AUD_FECHA        TIMESTAMP(6)                 DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO
)
LOB (FECHA_REGISTRO) STORE AS (
  TABLESPACE USERS
  ENABLE       STORAGE IN ROW
  CHUNK       8192
  RETENTION
  CACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.TPAR_TIPO_DOCUMENTO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.TPAR_TIPO_DOCUMENTO CASCADE CONSTRAINTS PURGE
/

--
-- TPAR_TIPO_DOCUMENTO  (Table) 
--
--   Row count:3
CREATE TABLE UAB_GET.TPAR_TIPO_DOCUMENTO
(
  ID_TIPO_DOCUMENTO  NUMBER(15)                 NOT NULL,
  DESCRIPCION        VARCHAR2(150 BYTE),
  APP_ID_USUARIO     NUMBER(15),
  AUD_ESTADO         NUMBER(1)                  DEFAULT 1,
  AUD_USUARIO        VARCHAR2(50 BYTE)          DEFAULT USER,
  AUD_FECHA          TIMESTAMP(6)               DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO     DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.TPAR_TIPO_FLOTA
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.TPAR_TIPO_FLOTA CASCADE CONSTRAINTS PURGE
/

--
-- TPAR_TIPO_FLOTA  (Table) 
--
--   Row count:4
CREATE TABLE UAB_GET.TPAR_TIPO_FLOTA
(
  ID_TIPO_FLOTA   NUMBER(15)                    NOT NULL,
  DESCRIPCION     VARCHAR2(100 BYTE),
  APP_ID_USUARIO  NUMBER(15),
  AUD_ESTADO      NUMBER(1)                     DEFAULT 1,
  AUD_USUARIO     VARCHAR2(50 BYTE)             DEFAULT USER,
  AUD_FECHA       TIMESTAMP(6)                  DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.TPAR_TIPO_PERSONA
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.TPAR_TIPO_PERSONA CASCADE CONSTRAINTS PURGE
/

--
-- TPAR_TIPO_PERSONA  (Table) 
--
--   Row count:2
CREATE TABLE UAB_GET.TPAR_TIPO_PERSONA
(
  ID_TIPO_PERSONA  NUMBER(15)                   NOT NULL,
  DESCRIPCION      VARCHAR2(150 BYTE),
  APP_ID_USUARIO   NUMBER(15),
  AUD_ESTADO       NUMBER(1)                    DEFAULT 1,
  AUD_USUARIO      VARCHAR2(50 BYTE)            DEFAULT USER,
  AUD_FECHA        TIMESTAMP(6)                 DEFAULT SYSTIMESTAMP,
  FECHA_REGSTRO    DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.TPAR_TIPO_USUARIO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.TPAR_TIPO_USUARIO CASCADE CONSTRAINTS PURGE
/

--
-- TPAR_TIPO_USUARIO  (Table) 
--
--   Row count:3
CREATE TABLE UAB_GET.TPAR_TIPO_USUARIO
(
  ID_TIPO_USUARIO  NUMBER(15)                   NOT NULL,
  DESCRIPCION      VARCHAR2(150 BYTE),
  APP_ID_USUARIO   NUMBER(15),
  AUD_ESTADO       NUMBER(1)                    DEFAULT 1,
  AUD_USUARIO      VARCHAR2(50 BYTE)            DEFAULT USER,
  AUD_FECHA        TIMESTAMP(6)                 DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO   DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.T_PERSONA
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.T_PERSONA CASCADE CONSTRAINTS PURGE
/

--
-- T_PERSONA  (Table) 
--
--   Row count:16
CREATE TABLE UAB_GET.T_PERSONA
(
  ID_PERSONA        NUMBER(15)                  NOT NULL,
  ID_TIPO_PERSONA   NUMBER(15),
  ID_GENERO         NUMBER(15),
  NOMBRE            VARCHAR2(100 BYTE),
  AP_PATERNO        VARCHAR2(100 BYTE),
  AP_MATERNO        VARCHAR2(100 BYTE),
  FECHA_NACIMIENTO  DATE,
  DIRECCION         VARCHAR2(150 BYTE),
  EMAIL             VARCHAR2(100 BYTE),
  APP_ID_USUARIO    NUMBER(15),
  AUD_ESTADO        NUMBER(1)                   DEFAULT 1,
  AUD_USUARIO       VARCHAR2(50 BYTE)           DEFAULT USER,
  AUD_FECHA         TIMESTAMP(6)                DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO    DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.T_USUARIO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.T_USUARIO CASCADE CONSTRAINTS PURGE
/

--
-- T_USUARIO  (Table) 
--
--   Row count:2
CREATE TABLE UAB_GET.T_USUARIO
(
  ID_USUARIO       NUMBER(15)                   NOT NULL,
  ID_PERSONA       NUMBER(15),
  ID_SUCURSAL      NUMBER(15),
  ID_TIPO_USUARIO  NUMBER(15),
  CLAVE            VARCHAR2(50 BYTE),
  USUARIO          VARCHAR2(50 BYTE),
  APP_ID_USUARIO   NUMBER(15),
  AUD_ESTADO       NUMBER(1)                    DEFAULT 1,
  AUD_USUARIO      VARCHAR2(50 BYTE)            DEFAULT USER,
  AUD_FECHA        TIMESTAMP(6)                 DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO   DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- PK_T_CAJERO  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_T_CAJERO ON UAB_GET.T_USUARIO
(ID_USUARIO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_T_CIUDAD  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_T_CIUDAD ON UAB_GET.T_CIUDAD
(ID_CIUDAD)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_T_FACTURA  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_T_FACTURA ON UAB_GET.T_FACTURA
(ID_FACTURA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_T_HORARIO  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_T_HORARIO ON UAB_GET.T_HORARIO
(ID_HORARIO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_TPAR_ESTADO_ASIENTO  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_TPAR_ESTADO_ASIENTO ON UAB_GET.TPAR_ESTADO_ASIENTO
(ID_ESTADO_ASIENTO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_TPAR_GENERO  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_TPAR_GENERO ON UAB_GET.TPAR_GENERO
(ID_GENERO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_TPAR_PRECIO  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_TPAR_PRECIO ON UAB_GET.TPAR_PRECIO
(ID_PRECIO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_TPAR_SUCURSAL  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_TPAR_SUCURSAL ON UAB_GET.TPAR_SUCURSAL
(ID_SUCURSAL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_TPAR_TIPO_ASIENTO  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_TPAR_TIPO_ASIENTO ON UAB_GET.TPAR_TIPO_ASIENTO
(ID_TIPO_ASIENTO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_TPAR_TIPO_DOCUMENTO  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_TPAR_TIPO_DOCUMENTO ON UAB_GET.TPAR_TIPO_DOCUMENTO
(ID_TIPO_DOCUMENTO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_TPAR_TIPO_FLOTA  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_TPAR_TIPO_FLOTA ON UAB_GET.TPAR_TIPO_FLOTA
(ID_TIPO_FLOTA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_TPAR_TIPO_PERSONA  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_TPAR_TIPO_PERSONA ON UAB_GET.TPAR_TIPO_PERSONA
(ID_TIPO_PERSONA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_TPAR_TIPO_USUARIO  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_TPAR_TIPO_USUARIO ON UAB_GET.TPAR_TIPO_USUARIO
(ID_TIPO_USUARIO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_T_PERSONA  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_T_PERSONA ON UAB_GET.T_PERSONA
(ID_PERSONA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- TPAR_ESTADO_A_ID_ESTADO_AS  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.TPAR_ESTADO_A_ID_ESTADO_AS 
    BEFORE INSERT 
    ON UAB_GET.TPAR_ESTADO_ASIENTO 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.TPAR_ESTADO_A_ID_ESTADO_AS.NEXTVAL 
        INTO :NEW.ID_ESTADO_ASIENTO 
        FROM DUAL; 
    END;
/


--
-- TPAR_GENERO_ID_GENERO  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.TPAR_GENERO_ID_GENERO 
    BEFORE INSERT 
    ON UAB_GET.TPAR_GENERO 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.TPAR_GENERO_ID_GENERO.NEXTVAL 
        INTO :NEW.ID_GENERO 
        FROM DUAL; 
    END;
/


--
-- TPAR_PRECIO_ID_PRECIO  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.TPAR_PRECIO_ID_PRECIO 
    BEFORE INSERT 
    ON UAB_GET.TPAR_PRECIO 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.TPAR_PRECIO_ID_PRECIO.NEXTVAL 
        INTO :NEW.ID_PRECIO 
        FROM DUAL; 
    END;
/


--
-- TPAR_SUCURSAL_ID_SUCURSAL  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.TPAR_SUCURSAL_ID_SUCURSAL 
    BEFORE INSERT 
    ON UAB_GET.TPAR_SUCURSAL 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.TPAR_SUCURSAL_ID_SUCURSAL.NEXTVAL 
        INTO :NEW.ID_SUCURSAL 
        FROM DUAL; 
    END;
/


--
-- TPAR_TIPO_ASI_ID_TIPO_ASIE  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.TPAR_TIPO_ASI_ID_TIPO_ASIE 
    BEFORE INSERT 
    ON UAB_GET.TPAR_TIPO_ASIENTO 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.TPAR_TIPO_ASI_ID_TIPO_ASIE.NEXTVAL 
        INTO :NEW.ID_TIPO_ASIENTO 
        FROM DUAL; 
    END;
/


--
-- TPAR_TIPO_DOC_ID_TIPO_DOCU  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.TPAR_TIPO_DOC_ID_TIPO_DOCU 
    BEFORE INSERT 
    ON UAB_GET.TPAR_TIPO_DOCUMENTO 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.TPAR_TIPO_DOC_ID_TIPO_DOCU.NEXTVAL 
        INTO :NEW.ID_TIPO_DOCUMENTO 
        FROM DUAL; 
    END;
/


--
-- TPAR_TIPO_FLO_ID_TIPO_FLOT  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.TPAR_TIPO_FLO_ID_TIPO_FLOT 
    BEFORE INSERT 
    ON UAB_GET.TPAR_TIPO_FLOTA 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.TPAR_TIPO_FLO_ID_TIPO_FLOT.NEXTVAL 
        INTO :NEW.ID_TIPO_FLOTA 
        FROM DUAL; 
    END;
/


--
-- TPAR_TIPO_PER_ID_TIPO_PERS  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.TPAR_TIPO_PER_ID_TIPO_PERS 
    BEFORE INSERT 
    ON UAB_GET.TPAR_TIPO_PERSONA 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.TPAR_TIPO_PER_ID_TIPO_PERS.NEXTVAL 
        INTO :NEW.ID_TIPO_PERSONA 
        FROM DUAL; 
    END;
/


--
-- TPAR_TIPO_USU_ID_TIPO_USUA  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.TPAR_TIPO_USU_ID_TIPO_USUA 
    BEFORE INSERT 
    ON UAB_GET.TPAR_TIPO_USUARIO 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.TPAR_TIPO_USU_ID_TIPO_USUA.NEXTVAL 
        INTO :NEW.ID_TIPO_USUARIO 
        FROM DUAL; 
    END;
/


--
-- T_CIUDAD_ID_CIUDAD  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.T_CIUDAD_ID_CIUDAD 
    BEFORE INSERT 
    ON UAB_GET.T_CIUDAD 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.T_CIUDAD_ID_CIUDAD.NEXTVAL 
        INTO :NEW.ID_CIUDAD 
        FROM DUAL; 
    END;
/


--
-- T_FACTURA_ID_FACTURA  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.T_FACTURA_ID_FACTURA 
    BEFORE INSERT 
    ON UAB_GET.T_FACTURA 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.T_FACTURA_ID_FACTURA.NEXTVAL 
        INTO :NEW.ID_FACTURA 
        FROM DUAL; 
    END;
/


--
-- T_HORARIO_ID_HORARIO  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.T_HORARIO_ID_HORARIO 
    BEFORE INSERT 
    ON UAB_GET.T_HORARIO 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.T_HORARIO_ID_HORARIO.NEXTVAL 
        INTO :NEW.ID_HORARIO 
        FROM DUAL; 
    END;
/


--
-- T_PERSONA_ID_PERSONA  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.T_PERSONA_ID_PERSONA 
    BEFORE INSERT 
    ON UAB_GET.T_PERSONA 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.T_PERSONA_ID_PERSONA.NEXTVAL 
        INTO :NEW.ID_PERSONA 
        FROM DUAL; 
    END;
/


--
-- T_USUARIO_ID_USUARIO  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.T_USUARIO_ID_USUARIO 
    BEFORE INSERT 
    ON UAB_GET.T_USUARIO 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.T_USUARIO_ID_USUARIO.NEXTVAL 
        INTO :NEW.ID_USUARIO 
        FROM DUAL; 
    END;
/


ALTER TABLE UAB_GET.T_ASIENTO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.T_ASIENTO CASCADE CONSTRAINTS PURGE
/

--
-- T_ASIENTO  (Table) 
--
--   Row count:6
CREATE TABLE UAB_GET.T_ASIENTO
(
  ID_ASIENTO       NUMBER(15)                   NOT NULL,
  ID_TIPO_ASIENTO  NUMBER(15),
  NUMERO           VARCHAR2(50 BYTE),
  APP_ID_USUARIO   NUMBER(15),
  AUD_ESTADO       NUMBER(1)                    DEFAULT 1,
  AUD_USUARIO      VARCHAR2(50 BYTE)            DEFAULT USER,
  AUD_FECHA        DATE                         DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO   DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.T_DOCUMENTO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.T_DOCUMENTO CASCADE CONSTRAINTS PURGE
/

--
-- T_DOCUMENTO  (Table) 
--
--   Row count:6
CREATE TABLE UAB_GET.T_DOCUMENTO
(
  ID_DOCUMENTO       NUMBER(15)                 NOT NULL,
  ID_PERSONA         NUMBER(15),
  ID_TIPO_DOCUMENTO  NUMBER(15),
  NUMERO_DOCUMENTO   VARCHAR2(50 BYTE),
  DESCRIPCION        VARCHAR2(150 BYTE),
  APP_ID_USUARIO     NUMBER(15),
  AUD_ESTADO         NUMBER(1)                  DEFAULT 1,
  AUD_USUARIO        VARCHAR2(50 BYTE)          DEFAULT USER,
  AUD_FECHA          TIMESTAMP(6)               DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO     DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.T_FLOTA
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.T_FLOTA CASCADE CONSTRAINTS PURGE
/

--
-- T_FLOTA  (Table) 
--
--   Row count:29
CREATE TABLE UAB_GET.T_FLOTA
(
  ID_FLOTA        NUMBER(15)                    NOT NULL,
  ID_TIPO_FLOTA   NUMBER(15),
  COLOR           VARCHAR2(50 BYTE),
  PLACA           VARCHAR2(50 BYTE),
  MODELO          VARCHAR2(50 BYTE),
  NRO_ASIENTOS    NUMBER(15),
  APP_ID_USUARIO  NUMBER(15),
  AUD_ESTADO      NUMBER(1)                     DEFAULT 1,
  AUD_USUARIO     VARCHAR2(50 BYTE)             DEFAULT USER,
  AUD_FECHA       TIMESTAMP(6)                  DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.T_RUTA
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.T_RUTA CASCADE CONSTRAINTS PURGE
/

--
-- T_RUTA  (Table) 
--
--   Row count:29
CREATE TABLE UAB_GET.T_RUTA
(
  ID_RUTA            NUMBER(15)                 NOT NULL,
  ID_CIUDAD_ORIGEN   NUMBER(15),
  ID_CIUDAD_DESTINO  NUMBER(15),
  ID_FLOTA           NUMBER(15),
  ID_HORARIO         NUMBER(15),
  ID_PRECIO          NUMBER(15,4),
  ID_CONDUCTOR       NUMBER(15),
  APP_ID_USUARIO     NUMBER(15),
  AUD_ESTADO         NUMBER(1)                  DEFAULT 1,
  AUD_USUARIO        VARCHAR2(50 BYTE)          DEFAULT USER,
  AUD_FECHA          TIMESTAMP(6)               DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO     DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- PK_T_ASIENTO  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_T_ASIENTO ON UAB_GET.T_ASIENTO
(ID_ASIENTO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_T_DOCUMENTO  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_T_DOCUMENTO ON UAB_GET.T_DOCUMENTO
(ID_DOCUMENTO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_T_FLOTA  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_T_FLOTA ON UAB_GET.T_FLOTA
(ID_FLOTA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_T_RUTA  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_T_RUTA ON UAB_GET.T_RUTA
(ID_RUTA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- T_ASIENTO_ID_ASIENTO  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.T_ASIENTO_ID_ASIENTO 
    BEFORE INSERT 
    ON UAB_GET.T_ASIENTO 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.T_ASIENTO_ID_ASIENTO.NEXTVAL 
        INTO :NEW.ID_ASIENTO 
        FROM DUAL; 
    END;
/


--
-- T_DOCUMENTO_ID_DOCUMENTO  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.T_DOCUMENTO_ID_DOCUMENTO 
    BEFORE INSERT 
    ON UAB_GET.T_DOCUMENTO 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.T_DOCUMENTO_ID_DOCUMENTO.NEXTVAL 
        INTO :NEW.ID_DOCUMENTO 
        FROM DUAL; 
    END;
/


--
-- T_FLOTA_ID_FLOTA  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.T_FLOTA_ID_FLOTA 
    BEFORE INSERT 
    ON UAB_GET.T_FLOTA 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.T_FLOTA_ID_FLOTA.NEXTVAL 
        INTO :NEW.ID_FLOTA 
        FROM DUAL; 
    END;
/


--
-- T_RUTA_ID_RUTA  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.T_RUTA_ID_RUTA 
    BEFORE INSERT 
    ON UAB_GET.T_RUTA 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.T_RUTA_ID_RUTA.NEXTVAL 
        INTO :NEW.ID_RUTA 
        FROM DUAL; 
    END;
/


ALTER TABLE UAB_GET.T_ASIENTO_RUTA
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.T_ASIENTO_RUTA CASCADE CONSTRAINTS PURGE
/

--
-- T_ASIENTO_RUTA  (Table) 
--
--   Row count:5
CREATE TABLE UAB_GET.T_ASIENTO_RUTA
(
  ID_ASIENTO_RUTA    NUMBER(15)                 NOT NULL,
  ID_RUTA            NUMBER(15),
  ID_ASIENTO         NUMBER(15),
  ID_ESTADO_ASIENTO  NUMBER(15),
  DESCRIPCION        VARCHAR2(1000 BYTE),
  APP_ID_USUARIO     NUMBER(15),
  AUD_ESTADO         NUMBER(1)                  DEFAULT 1,
  AUD_USUARIO        VARCHAR2(50 BYTE)          DEFAULT USER,
  AUD_FECHA          TIMESTAMP(6)               DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO     DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE UAB_GET.T_ASIENTO_RUTA IS 'Esta tabla almacena datos sobre los asientos ocupados/libres en una ruta'
/



ALTER TABLE UAB_GET.T_BOLETO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.T_BOLETO CASCADE CONSTRAINTS PURGE
/

--
-- T_BOLETO  (Table) 
--
--   Row count:5
CREATE TABLE UAB_GET.T_BOLETO
(
  ID_BOLETO       NUMBER(15)                    NOT NULL,
  ID_USUARIO      NUMBER(15),
  ID_RUTA         NUMBER(15),
  ID_SUCURSAL     NUMBER(15),
  APP_ID_USUARIO  NUMBER(15),
  AUD_ESTADO      NUMBER(1)                     DEFAULT 1,
  AUD_USUARIO     VARCHAR2(50 BYTE)             DEFAULT USER,
  AUD_FECHA       TIMESTAMP(6)                  DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE UAB_GET.T_DETALLE_BOLETO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE UAB_GET.T_DETALLE_BOLETO CASCADE CONSTRAINTS PURGE
/

--
-- T_DETALLE_BOLETO  (Table) 
--
--   Row count:4
CREATE TABLE UAB_GET.T_DETALLE_BOLETO
(
  ID_DETALLE_BOLETO  NUMBER(15)                 NOT NULL,
  ID_BOLETO          NUMBER(15),
  ID_ASIENTO         NUMBER(15),
  ID_PERSONA         NUMBER(15),
  APP_ID_USUARIO     NUMBER(15),
  AUD_ESTADO         NUMBER(1)                  DEFAULT 1,
  AUD_USUARIO        VARCHAR2(50 BYTE)          DEFAULT USER,
  AUD_FECHA          TIMESTAMP(6)               DEFAULT SYSTIMESTAMP,
  FECHA_REGISTRO     DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- PK_T_ASIENTO_RUTA  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_T_ASIENTO_RUTA ON UAB_GET.T_ASIENTO_RUTA
(ID_ASIENTO_RUTA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_T_BOLETO  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_T_BOLETO ON UAB_GET.T_BOLETO
(ID_BOLETO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- PK_T_DETALLE_BOLETO  (Index) 
--
CREATE UNIQUE INDEX UAB_GET.PK_T_DETALLE_BOLETO ON UAB_GET.T_DETALLE_BOLETO
(ID_DETALLE_BOLETO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- T_ASIENTO_RUT_ID_ASIENTO_R  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.T_ASIENTO_RUT_ID_ASIENTO_R 
    BEFORE INSERT 
    ON UAB_GET.T_ASIENTO_RUTA 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.T_ASIENTO_RUT_ID_ASIENTO_R.NEXTVAL 
        INTO :NEW.ID_ASIENTO_RUTA 
        FROM DUAL; 
    END;
/


--
-- T_BOLETO_ID_BOLETO  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.T_BOLETO_ID_BOLETO 
    BEFORE INSERT 
    ON UAB_GET.T_BOLETO 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.T_BOLETO_ID_BOLETO.NEXTVAL 
        INTO :NEW.ID_BOLETO 
        FROM DUAL; 
    END;
/


--
-- T_DETALLE_BOL_ID_DETALLE_B  (Trigger) 
--
CREATE OR REPLACE TRIGGER UAB_GET.T_DETALLE_BOL_ID_DETALLE_B 
    BEFORE INSERT 
    ON UAB_GET.T_DETALLE_BOLETO 
    FOR EACH ROW
BEGIN 
        SELECT UAB_GET.T_DETALLE_BOL_ID_DETALLE_B.NEXTVAL 
        INTO :NEW.ID_DETALLE_BOLETO 
        FROM DUAL; 
    END;
/


-- 
-- Non Foreign Key Constraints for Table T_CIUDAD 
-- 
ALTER TABLE UAB_GET.T_CIUDAD ADD (
  CONSTRAINT PK_T_CIUDAD
  PRIMARY KEY
  (ID_CIUDAD)
  USING INDEX UAB_GET.PK_T_CIUDAD
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table T_FACTURA 
-- 
ALTER TABLE UAB_GET.T_FACTURA ADD (
  CONSTRAINT PK_T_FACTURA
  PRIMARY KEY
  (ID_FACTURA)
  USING INDEX UAB_GET.PK_T_FACTURA
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table T_HORARIO 
-- 
ALTER TABLE UAB_GET.T_HORARIO ADD (
  CONSTRAINT PK_T_HORARIO
  PRIMARY KEY
  (ID_HORARIO)
  USING INDEX UAB_GET.PK_T_HORARIO
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table TPAR_ESTADO_ASIENTO 
-- 
ALTER TABLE UAB_GET.TPAR_ESTADO_ASIENTO ADD (
  CONSTRAINT PK_TPAR_ESTADO_ASIENTO
  PRIMARY KEY
  (ID_ESTADO_ASIENTO)
  USING INDEX UAB_GET.PK_TPAR_ESTADO_ASIENTO
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table TPAR_GENERO 
-- 
ALTER TABLE UAB_GET.TPAR_GENERO ADD (
  CONSTRAINT PK_TPAR_GENERO
  PRIMARY KEY
  (ID_GENERO)
  USING INDEX UAB_GET.PK_TPAR_GENERO
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table TPAR_PRECIO 
-- 
ALTER TABLE UAB_GET.TPAR_PRECIO ADD (
  CONSTRAINT PK_TPAR_PRECIO
  PRIMARY KEY
  (ID_PRECIO)
  USING INDEX UAB_GET.PK_TPAR_PRECIO
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table TPAR_SUCURSAL 
-- 
ALTER TABLE UAB_GET.TPAR_SUCURSAL ADD (
  CONSTRAINT PK_TPAR_SUCURSAL
  PRIMARY KEY
  (ID_SUCURSAL)
  USING INDEX UAB_GET.PK_TPAR_SUCURSAL
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table TPAR_TIPO_ASIENTO 
-- 
ALTER TABLE UAB_GET.TPAR_TIPO_ASIENTO ADD (
  CONSTRAINT PK_TPAR_TIPO_ASIENTO
  PRIMARY KEY
  (ID_TIPO_ASIENTO)
  USING INDEX UAB_GET.PK_TPAR_TIPO_ASIENTO
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table TPAR_TIPO_DOCUMENTO 
-- 
ALTER TABLE UAB_GET.TPAR_TIPO_DOCUMENTO ADD (
  CONSTRAINT PK_TPAR_TIPO_DOCUMENTO
  PRIMARY KEY
  (ID_TIPO_DOCUMENTO)
  USING INDEX UAB_GET.PK_TPAR_TIPO_DOCUMENTO
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table TPAR_TIPO_FLOTA 
-- 
ALTER TABLE UAB_GET.TPAR_TIPO_FLOTA ADD (
  CONSTRAINT PK_TPAR_TIPO_FLOTA
  PRIMARY KEY
  (ID_TIPO_FLOTA)
  USING INDEX UAB_GET.PK_TPAR_TIPO_FLOTA
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table TPAR_TIPO_PERSONA 
-- 
ALTER TABLE UAB_GET.TPAR_TIPO_PERSONA ADD (
  CONSTRAINT PK_TPAR_TIPO_PERSONA
  PRIMARY KEY
  (ID_TIPO_PERSONA)
  USING INDEX UAB_GET.PK_TPAR_TIPO_PERSONA
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table TPAR_TIPO_USUARIO 
-- 
ALTER TABLE UAB_GET.TPAR_TIPO_USUARIO ADD (
  CONSTRAINT PK_TPAR_TIPO_USUARIO
  PRIMARY KEY
  (ID_TIPO_USUARIO)
  USING INDEX UAB_GET.PK_TPAR_TIPO_USUARIO
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table T_PERSONA 
-- 
ALTER TABLE UAB_GET.T_PERSONA ADD (
  CONSTRAINT PK_T_PERSONA
  PRIMARY KEY
  (ID_PERSONA)
  USING INDEX UAB_GET.PK_T_PERSONA
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table T_USUARIO 
-- 
ALTER TABLE UAB_GET.T_USUARIO ADD (
  CONSTRAINT PK_T_CAJERO
  PRIMARY KEY
  (ID_USUARIO)
  USING INDEX UAB_GET.PK_T_CAJERO
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table T_ASIENTO 
-- 
ALTER TABLE UAB_GET.T_ASIENTO ADD (
  CONSTRAINT PK_T_ASIENTO
  PRIMARY KEY
  (ID_ASIENTO)
  USING INDEX UAB_GET.PK_T_ASIENTO
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table T_DOCUMENTO 
-- 
ALTER TABLE UAB_GET.T_DOCUMENTO ADD (
  CONSTRAINT PK_T_DOCUMENTO
  PRIMARY KEY
  (ID_DOCUMENTO)
  USING INDEX UAB_GET.PK_T_DOCUMENTO
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table T_FLOTA 
-- 
ALTER TABLE UAB_GET.T_FLOTA ADD (
  CONSTRAINT PK_T_FLOTA
  PRIMARY KEY
  (ID_FLOTA)
  USING INDEX UAB_GET.PK_T_FLOTA
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table T_RUTA 
-- 
ALTER TABLE UAB_GET.T_RUTA ADD (
  CONSTRAINT PK_T_RUTA
  PRIMARY KEY
  (ID_RUTA)
  USING INDEX UAB_GET.PK_T_RUTA
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table T_ASIENTO_RUTA 
-- 
ALTER TABLE UAB_GET.T_ASIENTO_RUTA ADD (
  CONSTRAINT PK_T_ASIENTO_RUTA
  PRIMARY KEY
  (ID_ASIENTO_RUTA)
  USING INDEX UAB_GET.PK_T_ASIENTO_RUTA
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table T_BOLETO 
-- 
ALTER TABLE UAB_GET.T_BOLETO ADD (
  CONSTRAINT PK_T_BOLETO
  PRIMARY KEY
  (ID_BOLETO)
  USING INDEX UAB_GET.PK_T_BOLETO
  ENABLE VALIDATE)
/

-- 
-- Non Foreign Key Constraints for Table T_DETALLE_BOLETO 
-- 
ALTER TABLE UAB_GET.T_DETALLE_BOLETO ADD (
  CONSTRAINT PK_T_DETALLE_BOLETO
  PRIMARY KEY
  (ID_DETALLE_BOLETO)
  USING INDEX UAB_GET.PK_T_DETALLE_BOLETO
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table T_PERSONA 
-- 
ALTER TABLE UAB_GET.T_PERSONA ADD (
  CONSTRAINT FK_PERS_GENE 
  FOREIGN KEY (ID_GENERO) 
  REFERENCES UAB_GET.TPAR_GENERO (ID_GENERO)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_TPAR_TIPE 
  FOREIGN KEY (ID_TIPO_PERSONA) 
  REFERENCES UAB_GET.TPAR_TIPO_PERSONA (ID_TIPO_PERSONA)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table T_USUARIO 
-- 
ALTER TABLE UAB_GET.T_USUARIO ADD (
  CONSTRAINT FK_USUA_PERS 
  FOREIGN KEY (ID_PERSONA) 
  REFERENCES UAB_GET.T_PERSONA (ID_PERSONA)
  ENABLE VALIDATE,
  CONSTRAINT FK_USUA_SUCU 
  FOREIGN KEY (ID_SUCURSAL) 
  REFERENCES UAB_GET.TPAR_SUCURSAL (ID_SUCURSAL)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_USUA_TIUS 
  FOREIGN KEY (ID_TIPO_USUARIO) 
  REFERENCES UAB_GET.TPAR_TIPO_USUARIO (ID_TIPO_USUARIO)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table T_ASIENTO 
-- 
ALTER TABLE UAB_GET.T_ASIENTO ADD (
  CONSTRAINT FK_ASIE_TIAS 
  FOREIGN KEY (ID_TIPO_ASIENTO) 
  REFERENCES UAB_GET.TPAR_TIPO_ASIENTO (ID_TIPO_ASIENTO)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table T_DOCUMENTO 
-- 
ALTER TABLE UAB_GET.T_DOCUMENTO ADD (
  CONSTRAINT FK_DOCU_PERS 
  FOREIGN KEY (ID_PERSONA) 
  REFERENCES UAB_GET.T_PERSONA (ID_PERSONA)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_DOCU_TIDO 
  FOREIGN KEY (ID_TIPO_DOCUMENTO) 
  REFERENCES UAB_GET.TPAR_TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table T_FLOTA 
-- 
ALTER TABLE UAB_GET.T_FLOTA ADD (
  CONSTRAINT FK_FLOT_TIFL 
  FOREIGN KEY (ID_TIPO_FLOTA) 
  REFERENCES UAB_GET.TPAR_TIPO_FLOTA (ID_TIPO_FLOTA)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table T_RUTA 
-- 
ALTER TABLE UAB_GET.T_RUTA ADD (
  CONSTRAINT FK_RUTA_CIDE 
  FOREIGN KEY (ID_CIUDAD_DESTINO) 
  REFERENCES UAB_GET.T_CIUDAD (ID_CIUDAD)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_RUTA_CIOR 
  FOREIGN KEY (ID_CIUDAD_ORIGEN) 
  REFERENCES UAB_GET.T_CIUDAD (ID_CIUDAD)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_RUTA_FLOT 
  FOREIGN KEY (ID_FLOTA) 
  REFERENCES UAB_GET.T_FLOTA (ID_FLOTA)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_RUTA_HORA 
  FOREIGN KEY (ID_HORARIO) 
  REFERENCES UAB_GET.T_HORARIO (ID_HORARIO)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_T_RUTA_TPAR_PRECIO 
  FOREIGN KEY (ID_PRECIO) 
  REFERENCES UAB_GET.TPAR_PRECIO (ID_PRECIO)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table T_ASIENTO_RUTA 
-- 
ALTER TABLE UAB_GET.T_ASIENTO_RUTA ADD (
  CONSTRAINT FK_ASIE_RUTA 
  FOREIGN KEY (ID_RUTA) 
  REFERENCES UAB_GET.T_RUTA (ID_RUTA)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_ASRU_ASIE 
  FOREIGN KEY (ID_ASIENTO) 
  REFERENCES UAB_GET.T_ASIENTO (ID_ASIENTO)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_ASRU_ESAS 
  FOREIGN KEY (ID_ESTADO_ASIENTO) 
  REFERENCES UAB_GET.TPAR_ESTADO_ASIENTO (ID_ESTADO_ASIENTO)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table T_BOLETO 
-- 
ALTER TABLE UAB_GET.T_BOLETO ADD (
  CONSTRAINT FK_BOLE_RUTA 
  FOREIGN KEY (ID_RUTA) 
  REFERENCES UAB_GET.T_RUTA (ID_RUTA)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_BOLE_SUCU 
  FOREIGN KEY (ID_SUCURSAL) 
  REFERENCES UAB_GET.TPAR_SUCURSAL (ID_SUCURSAL)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_BOLE_USUA 
  FOREIGN KEY (ID_USUARIO) 
  REFERENCES UAB_GET.T_USUARIO (ID_USUARIO)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table T_DETALLE_BOLETO 
-- 
ALTER TABLE UAB_GET.T_DETALLE_BOLETO ADD (
  CONSTRAINT FK_DEBO_ASIE 
  FOREIGN KEY (ID_ASIENTO) 
  REFERENCES UAB_GET.T_ASIENTO (ID_ASIENTO)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_DEBO_BOLE 
  FOREIGN KEY (ID_BOLETO) 
  REFERENCES UAB_GET.T_BOLETO (ID_BOLETO)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT FK_DEBO_PERS 
  FOREIGN KEY (ID_PERSONA) 
  REFERENCES UAB_GET.T_PERSONA (ID_PERSONA)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
