DROP PACKAGE APP_GESTION_UAB.PGET_GESTION
/

--
-- PGET_GESTION  (Package) 
--
CREATE OR REPLACE PACKAGE APP_GESTION_UAB.PGET_GESTION AS
/******************************************************************************
   NAME:       PGET_GESTION
   PURPOSE:
 
   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        23/03/2015      HENRRY       1. Created this package.
******************************************************************************/

PROCEDURE P_REGISTRAR_GENERO(
I_CREDENCIAL        IN  VARCHAR2,
I_ID_GENERO         IN NUMBER,
I_DESCRIPCION       IN VARCHAR2, 
I_APP_ID_USUARIO    IN NUMBER,
I_AUD_ESTADO        IN NUMBER,
I_FECHA_REGISTRO    IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
);
PROCEDURE P_REGISTRAR_PERSONA(
I_CREDENCIAL           IN  VARCHAR2,
I_ID_PERSONA           IN NUMBER, 
I_ID_TIPO_PERSONA      IN NUMBER, 
I_ID_GENERO            IN NUMBER,
I_NOMBRE               IN VARCHAR2,
I_AP_PATERNO           IN VARCHAR2,
I_AP_MATERNO           IN VARCHAR2,
I_FECHA_NACIMIENTO     IN DATE,
I_DIRECCION            IN VARCHAR2,
I_EMAIL                IN VARCHAR2,
I_APP_ID_USUARIO       IN NUMBER,
I_AUD_ESTADO           IN NUMBER,
I_FECHA_REGISTRO       IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
);

PROCEDURE P_REGISTRA_DOCUMENTO(
I_CREDENCIAL           IN  VARCHAR2,
I_ID_DOCUMENTO         IN NUMBER,
I_ID_PERSONA           IN NUMBER, 
I_ID_TIPO_DOCUMENTO    IN NUMBER,
I_NUMERO_DOCUMENTO     IN VARCHAR2,
I_DESCRIPCION          IN VARCHAR2,
I_APP_ID_USUARIO       IN NUMBER,
I_AUD_ESTADO           IN NUMBER,
I_FECHA_REGISTRO       IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
);
PROCEDURE P_REGISTRAR_BOLETO(
I_CREDENCIAL          IN  VARCHAR2,
I_ID_BOLETO           IN NUMBER,
I_ID_USUARIO          IN NUMBER,
I_ID_RUTA             IN NUMBER,
I_ID_SUCURSAL         IN NUMBER,
I_APP_ID_USUARIO      IN NUMBER,
I_AUD_ESTADO          IN NUMBER,
I_FECHA_REGISTRO      IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
);
PROCEDURE P_REGISTRAR_ASIENTO(
I_CREDENCIAL          IN  VARCHAR2,
I_ID_ASIENTO          IN NUMBER,
I_ID_TIPO_ASIENTO     IN NUMBER,
I_NUMERO              IN VARCHAR2,
I_APP_ID_USUARIO      IN NUMBER,
I_AUD_ESTADO          IN NUMBER,
I_FECHA_REGISTRO      IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
);

PROCEDURE P_REGISTRAR_DETALLE_BOLETO(
I_CREDENCIAL          IN  VARCHAR2,
I_ID_DETALLE_BOLETO   IN NUMBER,
I_ID_BOLETO           IN NUMBER,
I_ID_ASIENTO          IN NUMBER,
I_ID_PERSONA          IN NUMBER,
I_APP_ID_USUARIO      IN NUMBER,
I_AUD_ESTADO          IN NUMBER,
I_FECHA_REGISTRO      IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
);

PROCEDURE P_REGISTRAR_ASIENTO_RUTA(
I_CREDENCIAL          IN  VARCHAR2,
I_ID_ASIENTO_RUTA     IN NUMBER,
I_ID_RUTA             IN NUMBER,
I_ID_ASIENTO          IN NUMBER,
I_ID_ESTADO_ASIENTO   IN NUMBER,
I_DESCRIPCION         IN VARCHAR2,
I_APP_ID_USUARIO      IN NUMBER,
I_AUD_ESTADO          IN NUMBER,
I_FECHA_REGISTRO      IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
);
PROCEDURE P_REGISTRAR_RUTA(
I_CREDENCIAL          IN  VARCHAR2,
I_ID_RUTA           IN NUMBER,
I_ID_CIUDAD_ORIGEN  IN NUMBER,
I_ID_CIUDAD_DESTINO IN NUMBER,
I_ID_FLOTA          IN NUMBER,
I_ID_HORARIO        IN NUMBER,
I_ID_PRECIO         IN NUMBER,
I_ID_CONDUCTOR      IN NUMBER,
I_APP_ID_USUARIO      IN NUMBER,
I_AUD_ESTADO          IN NUMBER,
I_FECHA_REGISTRO      IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
);
END PGET_GESTION;
/

DROP PACKAGE APP_GESTION_UAB.PGET_LISTADOS
/

--
-- PGET_LISTADOS  (Package) 
--
CREATE OR REPLACE PACKAGE APP_GESTION_UAB.PGET_LISTADOS AS
/******************************************************************************
   NAME:       PGET_LISTADOS
   PURPOSE:

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        23/03/2015      HENRRY       1. Created this package.
******************************************************************************/
PROCEDURE P_LISTAR_GENERO ( 
I_CREDENCIAL        IN  VARCHAR2,
I_ID_GENERO         IN NUMBER,
I_DESCRIPCION       IN VARCHAR2, 
I_APP_ID_USUARIO    IN NUMBER,
I_AUD_ESTADO        IN NUMBER,
I_FECHA_REGISTRO    IN DATE,
O_LISTAR_GENERO  OUT SYS_REFCURSOR
);
PROCEDURE P_LISTAR_PERSONA ( 
    I_CREDENCIAL        IN VARCHAR2, 
    I_ID_PERSONA        IN NUMBER,
    I_ID_TIPO_PERSONA   IN NUMBER,
    I_TIPO_PERSONA      IN VARCHAR2,
    I_ID_GENERO         IN NUMBER,
    I_GENERO            IN VARCHAR2,
    I_NOMBRE            IN VARCHAR2,
    I_AP_PATERNO        IN VARCHAR2,
    I_AP_MATERNO        IN VARCHAR2,
    I_FECHA_NACIMIENTO  IN DATE,
    I_DIRECCION         IN VARCHAR2,
    I_EMAIL             IN VARCHAR2,
    I_APP_ID_USUARIO    IN NUMBER,
    I_AUD_ESTADO        IN NUMBER,
    I_FECHA_REGISTRO    IN DATE,
      
  O_LISTAR_PERSONA  OUT SYS_REFCURSOR
  );
  
PROCEDURE P_LISTAR_DOCUMENTO( 
I_CREDENCIAL        IN VARCHAR2,
I_ID_DOCUMENTO      IN NUMBER,
I_ID_PERSONA          IN NUMBER, 
I_ID_TIPO_DOCUMENTO   IN NUMBER,
I_TIPO_DOCUMENTO      IN VARCHAR2,
I_NUMERO_DOCUMENTO    IN VARCHAR2,
I_DESCRIPCION         IN VARCHAR2,
I_APP_ID_USUARIO      IN NUMBER,
I_AUD_ESTADO          IN NUMBER,
I_FECHA_REGISTRO      IN DATE,

O_LISTAR_DOCUMENTO  OUT SYS_REFCURSOR
);
 PROCEDURE P_LISTAR_BOLETO_COMPLETO(
 I_CREDENCIAL   IN VARCHAR2,
    I_ID_BOLETO          IN NUMBER,
    I_ID_RUTA            IN NUMBER,   
    I_ID_USUARIO         IN NUMBER,
    I_ID_SUCURSAL        IN NUMBER,
    I_FECHA_REGISTRO     IN DATE,
    I_AUD_ESTADO         IN NUMBER,
    I_ID_DETALLE_BOLETO  IN NUMBER,
    I_ID_ASIENTO         IN NUMBER,
    I_ID_PERSONA         IN NUMBER,
    I_ID_TIPO_ASIENTO    IN NUMBER,
    I_NUMERO             IN VARCHAR2,
    I_TIPO_ASIENTO       IN VARCHAR2,
 O_LISTAR_BOLETO_COMPLETO  OUT SYS_REFCURSOR          
 );   
PROCEDURE P_LISTAR_ASIENTO_COMPLETO(
 I_CREDENCIAL   IN VARCHAR2,
   I_ID_ASIENTO_RUTA       IN NUMBER,
   I_ID_RUTA               IN NUMBER,
   I_ID_ESTADO_ASIENTO     IN NUMBER,
   I_ASIENTO_RUTA          IN VARCHAR2,
   I_AUD_ESTADO            IN NUMBER,
   I_FECHA_REGISTRO        IN DATE,
   I_ID_ASIENTO            IN NUMBER,
   I_ESTADO_ASIENTO        IN VARCHAR2,
   I_NUMERO                IN VARCHAR2,
   I_TIPO_ASIENTO          IN VARCHAR2,
   I_ID_TIPO_ASIENTO       IN NUMBER,
 O_LISTAR_ASIENTO_COMPLETO  OUT SYS_REFCURSOR          
 );
 
 PROCEDURE P_LISTAR_RUTA_COMPLETO(
 I_CREDENCIAL   IN VARCHAR2,
I_ID_RUTA            IN NUMBER,
I_ID_CIUDAD_ORIGEN   IN NUMBER,
I_ID_CIUDAD_DESTINO  IN NUMBER,
I_ID_FLOTA           IN NUMBER,
I_ID_HORARIO         IN NUMBER,
I_ID_PRECIO          IN NUMBER,
I_ID_CONDUCTOR       IN NUMBER,

I_PRECIO             IN NUMBER,
I_HORA               IN VARCHAR2,
I_ID_TIPO_FLOTA      IN NUMBER,
I_PLACA              IN VARCHAR2,
I_MODELO             IN VARCHAR2,
I_NRO_ASIENTOS       IN NUMBER,
I_TIPO_FLOTA         IN VARCHAR2,
I_AUD_ESTADO         IN NUMBER,
 O_LISTAR_RUTA_COMPLETO  OUT SYS_REFCURSOR          
 );

PROCEDURE P_LISTAR_CIUDAD ( 
I_CREDENCIAL        IN  VARCHAR2,
I_ID_CIUDAD         IN NUMBER,
I_CIUDAD            IN VARCHAR2, 
I_AUD_ESTADO        IN NUMBER,
O_LISTAR_CIUDAD  OUT SYS_REFCURSOR
);
END PGET_LISTADOS;
/
DROP PACKAGE BODY APP_GESTION_UAB.PGET_GESTION
/

--
-- PGET_GESTION  (Package Body) 
--
CREATE OR REPLACE PACKAGE BODY APP_GESTION_UAB.PGET_GESTION AS
/******************************************************************************
   NAME:       PGET_GESTION
   PURPOSE:
 
   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        23/03/2015      HENRRY       1. Created this package body.
******************************************************************************/
PROCEDURE P_REGISTRAR_GENERO(
I_CREDENCIAL        IN  VARCHAR2,
I_ID_GENERO         IN NUMBER,
I_DESCRIPCION       IN VARCHAR2, 
I_APP_ID_USUARIO    IN NUMBER,
I_AUD_ESTADO        IN NUMBER,
I_FECHA_REGISTRO    IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
)IS
BEGIN
UAB_GET.PGET_GESTION.P_REGISTRAR_GENERO(
    I_CREDENCIAL, 
    I_ID_GENERO, 
    I_DESCRIPCION, 
    I_APP_ID_USUARIO, 
    I_AUD_ESTADO, 
    I_FECHA_REGISTRO, 
    O_RESULTADO
    );
END;
   
PROCEDURE P_REGISTRAR_PERSONA(
I_CREDENCIAL           IN  VARCHAR2,
I_ID_PERSONA           IN NUMBER, 
I_ID_TIPO_PERSONA      IN NUMBER, 
I_ID_GENERO            IN NUMBER,
I_NOMBRE               IN VARCHAR2,
I_AP_PATERNO           IN VARCHAR2,
I_AP_MATERNO           IN VARCHAR2,
I_FECHA_NACIMIENTO     IN DATE,
I_DIRECCION            IN VARCHAR2,
I_EMAIL                IN VARCHAR2,
I_APP_ID_USUARIO       IN NUMBER,
I_AUD_ESTADO           IN NUMBER,
I_FECHA_REGISTRO       IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
)IS
BEGIN
    UAB_GET.PGET_GESTION.P_REGISTRAR_PERSONA(
            I_CREDENCIAL, 
            I_ID_PERSONA, 
            I_ID_TIPO_PERSONA, 
            I_ID_GENERO, 
            I_NOMBRE, 
            I_AP_PATERNO, 
            I_AP_MATERNO, 
            I_FECHA_NACIMIENTO, 
            I_DIRECCION, 
            I_EMAIL, 
            I_APP_ID_USUARIO, 
            I_AUD_ESTADO, 
            I_FECHA_REGISTRO, 
            O_RESULTADO
            );
END;

PROCEDURE P_REGISTRA_DOCUMENTO(
I_CREDENCIAL           IN  VARCHAR2,
I_ID_DOCUMENTO         IN NUMBER,
I_ID_PERSONA           IN NUMBER, 
I_ID_TIPO_DOCUMENTO    IN NUMBER,
I_NUMERO_DOCUMENTO     IN VARCHAR2,
I_DESCRIPCION          IN VARCHAR2,
I_APP_ID_USUARIO       IN NUMBER,
I_AUD_ESTADO           IN NUMBER,
I_FECHA_REGISTRO       IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
)IS
BEGIN
    UAB_GET.PGET_GESTION.P_REGISTRA_DOCUMENTO(
        I_CREDENCIAL, 
        I_ID_DOCUMENTO, 
        I_ID_PERSONA, 
        I_ID_TIPO_DOCUMENTO, 
        I_NUMERO_DOCUMENTO, 
        I_DESCRIPCION, 
        I_APP_ID_USUARIO, 
        I_AUD_ESTADO, 
        I_FECHA_REGISTRO, 
        O_RESULTADO
        );      
END;

PROCEDURE P_REGISTRAR_BOLETO(
I_CREDENCIAL          IN  VARCHAR2,
I_ID_BOLETO           IN NUMBER,
I_ID_USUARIO          IN NUMBER,
I_ID_RUTA             IN NUMBER,
I_ID_SUCURSAL         IN NUMBER,
I_APP_ID_USUARIO      IN NUMBER,
I_AUD_ESTADO          IN NUMBER,
I_FECHA_REGISTRO      IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
)IS
BEGIN
    UAB_GET.PGET_GESTION.P_REGISTRAR_BOLETO(
        I_CREDENCIAL, 
        I_ID_BOLETO, 
        I_ID_USUARIO, 
        I_ID_RUTA, 
        I_ID_SUCURSAL, 
        I_APP_ID_USUARIO, 
        I_AUD_ESTADO, 
        I_FECHA_REGISTRO, 
        O_RESULTADO
        );
END;

PROCEDURE P_REGISTRAR_ASIENTO(
I_CREDENCIAL          IN  VARCHAR2,
I_ID_ASIENTO          IN NUMBER,
I_ID_TIPO_ASIENTO     IN NUMBER,
I_NUMERO              IN VARCHAR2,
I_APP_ID_USUARIO      IN NUMBER,
I_AUD_ESTADO          IN NUMBER,
I_FECHA_REGISTRO      IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
)IS
BEGIN
    UAB_GET.PGET_GESTION.P_REGISTRAR_ASIENTO(
        I_CREDENCIAL, 
        I_ID_ASIENTO, 
        I_ID_TIPO_ASIENTO, 
        I_NUMERO, 
        I_APP_ID_USUARIO, 
        I_AUD_ESTADO, 
        I_FECHA_REGISTRO, 
        O_RESULTADO
        );
END;

PROCEDURE P_REGISTRAR_DETALLE_BOLETO(
I_CREDENCIAL          IN  VARCHAR2,
I_ID_DETALLE_BOLETO   IN NUMBER,
I_ID_BOLETO           IN NUMBER,
I_ID_ASIENTO          IN NUMBER,
I_ID_PERSONA          IN NUMBER,
I_APP_ID_USUARIO      IN NUMBER,
I_AUD_ESTADO          IN NUMBER,
I_FECHA_REGISTRO      IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
)IS
BEGIN
    UAB_GET.PGET_GESTION.P_REGISTRAR_DETALLE_BOLETO(
        I_CREDENCIAL, 
        I_ID_DETALLE_BOLETO, 
        I_ID_BOLETO, 
        I_ID_ASIENTO, 
        I_ID_PERSONA, 
        I_APP_ID_USUARIO, 
        I_AUD_ESTADO, 
        I_FECHA_REGISTRO, 
        O_RESULTADO
        );
END;

PROCEDURE P_REGISTRAR_ASIENTO_RUTA(
I_CREDENCIAL          IN  VARCHAR2,
I_ID_ASIENTO_RUTA     IN NUMBER,
I_ID_RUTA             IN NUMBER,
I_ID_ASIENTO          IN NUMBER,
I_ID_ESTADO_ASIENTO   IN NUMBER,
I_DESCRIPCION         IN VARCHAR2,
I_APP_ID_USUARIO      IN NUMBER,
I_AUD_ESTADO          IN NUMBER,
I_FECHA_REGISTRO      IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
)IS
BEGIN
    UAB_GET.PGET_GESTION.P_REGISTRAR_ASIENTO_RUTA(
        I_CREDENCIAL, 
        I_ID_ASIENTO_RUTA, 
        I_ID_RUTA, 
        I_ID_ASIENTO, 
        I_ID_ESTADO_ASIENTO, 
        I_DESCRIPCION, 
        I_APP_ID_USUARIO, 
        I_AUD_ESTADO, 
        I_FECHA_REGISTRO, 
        O_RESULTADO
        );
END;

PROCEDURE P_REGISTRAR_RUTA(
I_CREDENCIAL          IN  VARCHAR2,
I_ID_RUTA           IN NUMBER,
I_ID_CIUDAD_ORIGEN  IN NUMBER,
I_ID_CIUDAD_DESTINO IN NUMBER,
I_ID_FLOTA          IN NUMBER,
I_ID_HORARIO        IN NUMBER,
I_ID_PRECIO         IN NUMBER,
I_ID_CONDUCTOR      IN NUMBER,
I_APP_ID_USUARIO      IN NUMBER,
I_AUD_ESTADO          IN NUMBER,
I_FECHA_REGISTRO      IN DATE,
O_RESULTADO OUT SYS_REFCURSOR
)IS
BEGIN
    UAB_GET.PGET_GESTION.P_REGISTRAR_RUTA(
        I_CREDENCIAL, 
        I_ID_RUTA, 
        I_ID_CIUDAD_ORIGEN, 
        I_ID_CIUDAD_DESTINO, 
        I_ID_FLOTA, 
        I_ID_HORARIO, 
        I_ID_PRECIO, 
        I_ID_CONDUCTOR, 
        I_APP_ID_USUARIO, 
        I_AUD_ESTADO, 
        I_FECHA_REGISTRO, 
        O_RESULTADO
        );
END;
END PGET_GESTION;
/

DROP PACKAGE BODY APP_GESTION_UAB.PGET_LISTADOS
/

--
-- PGET_LISTADOS  (Package Body) 
--
CREATE OR REPLACE PACKAGE BODY APP_GESTION_UAB.PGET_LISTADOS AS
/******************************************************************************
   NAME:       PGET_LISTADOS
   PURPOSE:

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        23/03/2015      HENRRY       1. Created this package body.
******************************************************************************/

PROCEDURE P_LISTAR_GENERO ( 
I_CREDENCIAL        IN  VARCHAR2,
I_ID_GENERO         IN NUMBER,
I_DESCRIPCION       IN VARCHAR2, 
I_APP_ID_USUARIO    IN NUMBER,
I_AUD_ESTADO        IN NUMBER,
I_FECHA_REGISTRO    IN DATE,
O_LISTAR_GENERO  OUT SYS_REFCURSOR
)
IS
  BEGIN
    UAB_GET.PGET_LISTADOS.P_LISTAR_GENERO(
        I_CREDENCIAL, 
        I_ID_GENERO, 
        I_DESCRIPCION, 
        I_APP_ID_USUARIO, 
        I_AUD_ESTADO, 
        I_FECHA_REGISTRO, 
        O_LISTAR_GENERO
        );
  END;

PROCEDURE P_LISTAR_PERSONA ( 
    I_CREDENCIAL        IN VARCHAR2, 
    I_ID_PERSONA        IN NUMBER,
    I_ID_TIPO_PERSONA   IN NUMBER,
    I_TIPO_PERSONA      IN VARCHAR2,
    I_ID_GENERO         IN NUMBER,
    I_GENERO            IN VARCHAR2,
    I_NOMBRE            IN VARCHAR2,
    I_AP_PATERNO        IN VARCHAR2,
    I_AP_MATERNO        IN VARCHAR2,
    I_FECHA_NACIMIENTO  IN DATE,
    I_DIRECCION         IN VARCHAR2,
    I_EMAIL             IN VARCHAR2,
    I_APP_ID_USUARIO    IN NUMBER,
    I_AUD_ESTADO        IN NUMBER,
    I_FECHA_REGISTRO    IN DATE,
      
  O_LISTAR_PERSONA  OUT SYS_REFCURSOR
  )
  IS
  BEGIN
    UAB_GET.PGET_LISTADOS.P_LISTAR_PERSONA(
        I_CREDENCIAL, 
        I_ID_PERSONA, 
        I_ID_TIPO_PERSONA, 
        I_TIPO_PERSONA, 
        I_ID_GENERO, 
        I_GENERO, 
        I_NOMBRE, 
        I_AP_PATERNO, 
        I_AP_MATERNO, 
        I_FECHA_NACIMIENTO, 
        I_DIRECCION, 
        I_EMAIL, 
        I_APP_ID_USUARIO, 
        I_AUD_ESTADO, 
        I_FECHA_REGISTRO, 
        O_LISTAR_PERSONA
        );
  END;

PROCEDURE P_LISTAR_DOCUMENTO( 
I_CREDENCIAL        IN VARCHAR2,
I_ID_DOCUMENTO      IN NUMBER,
I_ID_PERSONA          IN NUMBER, 
I_ID_TIPO_DOCUMENTO   IN NUMBER,
I_TIPO_DOCUMENTO      IN VARCHAR2,
I_NUMERO_DOCUMENTO    IN VARCHAR2,
I_DESCRIPCION         IN VARCHAR2,
I_APP_ID_USUARIO      IN NUMBER,
I_AUD_ESTADO          IN NUMBER,
I_FECHA_REGISTRO      IN DATE,

O_LISTAR_DOCUMENTO  OUT SYS_REFCURSOR
)IS
BEGIN
    UAB_GET.PGET_LISTADOS.P_LISTAR_DOCUMENTO(
        I_CREDENCIAL, 
        I_ID_DOCUMENTO, 
        I_ID_PERSONA, 
        I_ID_TIPO_DOCUMENTO, 
        I_TIPO_DOCUMENTO, 
        I_NUMERO_DOCUMENTO, 
        I_DESCRIPCION, 
        I_APP_ID_USUARIO, 
        I_AUD_ESTADO, 
        I_FECHA_REGISTRO, 
        O_LISTAR_DOCUMENTO
        );
END;


 PROCEDURE P_LISTAR_BOLETO_COMPLETO(
 I_CREDENCIAL   IN VARCHAR2,
    I_ID_BOLETO          IN NUMBER,
    I_ID_RUTA            IN NUMBER,   
    I_ID_USUARIO         IN NUMBER,
    I_ID_SUCURSAL        IN NUMBER,
    I_FECHA_REGISTRO     IN DATE,
    I_AUD_ESTADO         IN NUMBER,
    I_ID_DETALLE_BOLETO  IN NUMBER,
    I_ID_ASIENTO         IN NUMBER,
    I_ID_PERSONA         IN NUMBER,
    I_ID_TIPO_ASIENTO    IN NUMBER,
    I_NUMERO             IN VARCHAR2,
    I_TIPO_ASIENTO       IN VARCHAR2,
 O_LISTAR_BOLETO_COMPLETO  OUT SYS_REFCURSOR          
 )IS
BEGIN
    UAB_GET.PGET_LISTADOS.P_LISTAR_BOLETO_COMPLETO(
        I_CREDENCIAL, 
        I_ID_BOLETO, 
        I_ID_RUTA, 
        I_ID_USUARIO, 
        I_ID_SUCURSAL, 
        I_FECHA_REGISTRO, 
        I_AUD_ESTADO, 
        I_ID_DETALLE_BOLETO, 
        I_ID_ASIENTO, 
        I_ID_PERSONA, 
        I_ID_TIPO_ASIENTO, 
        I_NUMERO, 
        I_TIPO_ASIENTO, 
        O_LISTAR_BOLETO_COMPLETO
        );
    
END;


PROCEDURE P_LISTAR_ASIENTO_COMPLETO(
 I_CREDENCIAL   IN VARCHAR2,
   I_ID_ASIENTO_RUTA       IN NUMBER,
   I_ID_RUTA               IN NUMBER,
   I_ID_ESTADO_ASIENTO     IN NUMBER,
   I_ASIENTO_RUTA          IN VARCHAR2,
   I_AUD_ESTADO            IN NUMBER,
   I_FECHA_REGISTRO        IN DATE,
   I_ID_ASIENTO            IN NUMBER,
   I_ESTADO_ASIENTO        IN VARCHAR2,
   I_NUMERO                IN VARCHAR2,
   I_TIPO_ASIENTO          IN VARCHAR2,
   I_ID_TIPO_ASIENTO       IN NUMBER,
 O_LISTAR_ASIENTO_COMPLETO  OUT SYS_REFCURSOR          
 )IS
BEGIN
    UAB_GET.PGET_LISTADOS.P_LISTAR_ASIENTO_COMPLETO(
        I_CREDENCIAL, 
        I_ID_ASIENTO_RUTA, 
        I_ID_RUTA, 
        I_ID_ESTADO_ASIENTO, 
        I_ASIENTO_RUTA, 
        I_AUD_ESTADO, 
        I_FECHA_REGISTRO, 
        I_ID_ASIENTO, 
        I_ESTADO_ASIENTO, 
        I_NUMERO, 
        I_TIPO_ASIENTO, 
        I_ID_TIPO_ASIENTO, 
        O_LISTAR_ASIENTO_COMPLETO
        );
    
END;


PROCEDURE P_LISTAR_RUTA_COMPLETO(
 I_CREDENCIAL   IN VARCHAR2,
I_ID_RUTA            IN NUMBER,
I_ID_CIUDAD_ORIGEN   IN NUMBER,
I_ID_CIUDAD_DESTINO  IN NUMBER,
I_ID_FLOTA           IN NUMBER,
I_ID_HORARIO         IN NUMBER,
I_ID_PRECIO          IN NUMBER,
I_ID_CONDUCTOR       IN NUMBER,

I_PRECIO             IN NUMBER,
I_HORA               IN VARCHAR2,
I_ID_TIPO_FLOTA      IN NUMBER,
I_PLACA              IN VARCHAR2,
I_MODELO             IN VARCHAR2,
I_NRO_ASIENTOS       IN NUMBER,
I_TIPO_FLOTA         IN VARCHAR2,
I_AUD_ESTADO         IN NUMBER,
 O_LISTAR_RUTA_COMPLETO  OUT SYS_REFCURSOR          
 )IS
BEGIN
    UAB_GET.PGET_LISTADOS.P_LISTAR_RUTA_COMPLETO(
        I_CREDENCIAL, 
        I_ID_RUTA, 
        I_ID_CIUDAD_ORIGEN, 
        I_ID_CIUDAD_DESTINO, 
        I_ID_FLOTA, 
        I_ID_HORARIO, 
        I_ID_PRECIO, 
        I_ID_CONDUCTOR, 
        I_PRECIO, 
        I_HORA, 
        I_ID_TIPO_FLOTA, 
        I_PLACA, 
        I_MODELO, 
        I_NRO_ASIENTOS, 
        I_TIPO_FLOTA, 
        I_AUD_ESTADO, 
        O_LISTAR_RUTA_COMPLETO
        );
END;

PROCEDURE P_LISTAR_CIUDAD ( 
I_CREDENCIAL        IN  VARCHAR2,
I_ID_CIUDAD         IN NUMBER,
I_CIUDAD            IN VARCHAR2, 
I_AUD_ESTADO        IN NUMBER,
O_LISTAR_CIUDAD  OUT SYS_REFCURSOR
) 
IS
  BEGIN
    UAB_GET.PGET_LISTADOS.P_LISTAR_CIUDAD(
        I_CREDENCIAL, 
        I_ID_CIUDAD, 
        I_CIUDAD, 
        I_AUD_ESTADO, 
        O_LISTAR_CIUDAD
        );
  END;

END PGET_LISTADOS;
/
