SET DEFINE OFF;
MERGE INTO UAB_GET.T_ASIENTO A USING
 (SELECT
  6 as ID_ASIENTO,
  1 as ID_TIPO_ASIENTO,
  '30' as NUMERO,
  999 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'APP_GESTION_UAB' as AUD_USUARIO,
  TO_DATE('04/23/2015 17:02:32', 'MM/DD/YYYY HH24:MI:SS') as AUD_FECHA,
  TO_DATE('04/23/2015 17:02:00', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_ASIENTO = B.ID_ASIENTO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_ASIENTO, ID_TIPO_ASIENTO, NUMERO, APP_ID_USUARIO, AUD_ESTADO, 
  AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_ASIENTO, B.ID_TIPO_ASIENTO, B.NUMERO, B.APP_ID_USUARIO, B.AUD_ESTADO, 
  B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_ASIENTO = B.ID_TIPO_ASIENTO,
  A.NUMERO = B.NUMERO,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_ASIENTO A USING
 (SELECT
  1 as ID_ASIENTO,
  2 as ID_TIPO_ASIENTO,
  '1' as NUMERO,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_DATE('04/20/2015 14:15:57', 'MM/DD/YYYY HH24:MI:SS') as AUD_FECHA,
  TO_DATE('04/20/2015 02:15:55', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_ASIENTO = B.ID_ASIENTO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_ASIENTO, ID_TIPO_ASIENTO, NUMERO, APP_ID_USUARIO, AUD_ESTADO, 
  AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_ASIENTO, B.ID_TIPO_ASIENTO, B.NUMERO, B.APP_ID_USUARIO, B.AUD_ESTADO, 
  B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_ASIENTO = B.ID_TIPO_ASIENTO,
  A.NUMERO = B.NUMERO,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_ASIENTO A USING
 (SELECT
  2 as ID_ASIENTO,
  1 as ID_TIPO_ASIENTO,
  '2' as NUMERO,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_DATE('04/20/2015 14:16:10', 'MM/DD/YYYY HH24:MI:SS') as AUD_FECHA,
  TO_DATE('04/20/2015 02:15:55', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_ASIENTO = B.ID_ASIENTO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_ASIENTO, ID_TIPO_ASIENTO, NUMERO, APP_ID_USUARIO, AUD_ESTADO, 
  AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_ASIENTO, B.ID_TIPO_ASIENTO, B.NUMERO, B.APP_ID_USUARIO, B.AUD_ESTADO, 
  B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_ASIENTO = B.ID_TIPO_ASIENTO,
  A.NUMERO = B.NUMERO,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_ASIENTO A USING
 (SELECT
  3 as ID_ASIENTO,
  1 as ID_TIPO_ASIENTO,
  '3' as NUMERO,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_DATE('04/20/2015 14:16:25', 'MM/DD/YYYY HH24:MI:SS') as AUD_FECHA,
  TO_DATE('04/20/2015 02:15:55', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_ASIENTO = B.ID_ASIENTO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_ASIENTO, ID_TIPO_ASIENTO, NUMERO, APP_ID_USUARIO, AUD_ESTADO, 
  AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_ASIENTO, B.ID_TIPO_ASIENTO, B.NUMERO, B.APP_ID_USUARIO, B.AUD_ESTADO, 
  B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_ASIENTO = B.ID_TIPO_ASIENTO,
  A.NUMERO = B.NUMERO,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_ASIENTO A USING
 (SELECT
  4 as ID_ASIENTO,
  2 as ID_TIPO_ASIENTO,
  '4' as NUMERO,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_DATE('04/20/2015 14:16:36', 'MM/DD/YYYY HH24:MI:SS') as AUD_FECHA,
  TO_DATE('04/20/2015 02:15:55', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_ASIENTO = B.ID_ASIENTO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_ASIENTO, ID_TIPO_ASIENTO, NUMERO, APP_ID_USUARIO, AUD_ESTADO, 
  AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_ASIENTO, B.ID_TIPO_ASIENTO, B.NUMERO, B.APP_ID_USUARIO, B.AUD_ESTADO, 
  B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_ASIENTO = B.ID_TIPO_ASIENTO,
  A.NUMERO = B.NUMERO,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_ASIENTO A USING
 (SELECT
  5 as ID_ASIENTO,
  2 as ID_TIPO_ASIENTO,
  '5' as NUMERO,
  555 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_DATE('04/20/2015 17:03:57', 'MM/DD/YYYY HH24:MI:SS') as AUD_FECHA,
  NULL as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_ASIENTO = B.ID_ASIENTO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_ASIENTO, ID_TIPO_ASIENTO, NUMERO, APP_ID_USUARIO, AUD_ESTADO, 
  AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_ASIENTO, B.ID_TIPO_ASIENTO, B.NUMERO, B.APP_ID_USUARIO, B.AUD_ESTADO, 
  B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_ASIENTO = B.ID_TIPO_ASIENTO,
  A.NUMERO = B.NUMERO,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

COMMIT;
