SET DEFINE OFF;
MERGE INTO UAB_GET.T_BOLETO A USING
 (SELECT
  6 as ID_BOLETO,
  2 as ID_USUARIO,
  5 as ID_RUTA,
  4 as ID_SUCURSAL,
  999 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'APP_GESTION_UAB' as AUD_USUARIO,
  TO_TIMESTAMP('23/04/2015 03:30:48.422000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/23/2015 15:30:00', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_BOLETO = B.ID_BOLETO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_BOLETO, ID_USUARIO, ID_RUTA, ID_SUCURSAL, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_BOLETO, B.ID_USUARIO, B.ID_RUTA, B.ID_SUCURSAL, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_USUARIO = B.ID_USUARIO,
  A.ID_RUTA = B.ID_RUTA,
  A.ID_SUCURSAL = B.ID_SUCURSAL,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_BOLETO A USING
 (SELECT
  1 as ID_BOLETO,
  2 as ID_USUARIO,
  5 as ID_RUTA,
  2 as ID_SUCURSAL,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('20/04/2015 01:46:32.000000 AM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:46:32', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_BOLETO = B.ID_BOLETO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_BOLETO, ID_USUARIO, ID_RUTA, ID_SUCURSAL, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_BOLETO, B.ID_USUARIO, B.ID_RUTA, B.ID_SUCURSAL, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_USUARIO = B.ID_USUARIO,
  A.ID_RUTA = B.ID_RUTA,
  A.ID_SUCURSAL = B.ID_SUCURSAL,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_BOLETO A USING
 (SELECT
  2 as ID_BOLETO,
  3 as ID_USUARIO,
  6 as ID_RUTA,
  4 as ID_SUCURSAL,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('20/04/2015 01:47:31.369000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:46:32', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_BOLETO = B.ID_BOLETO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_BOLETO, ID_USUARIO, ID_RUTA, ID_SUCURSAL, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_BOLETO, B.ID_USUARIO, B.ID_RUTA, B.ID_SUCURSAL, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_USUARIO = B.ID_USUARIO,
  A.ID_RUTA = B.ID_RUTA,
  A.ID_SUCURSAL = B.ID_SUCURSAL,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_BOLETO A USING
 (SELECT
  4 as ID_BOLETO,
  3 as ID_USUARIO,
  6 as ID_RUTA,
  4 as ID_SUCURSAL,
  888 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('20/04/2015 01:51:01.749000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  NULL as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_BOLETO = B.ID_BOLETO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_BOLETO, ID_USUARIO, ID_RUTA, ID_SUCURSAL, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_BOLETO, B.ID_USUARIO, B.ID_RUTA, B.ID_SUCURSAL, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_USUARIO = B.ID_USUARIO,
  A.ID_RUTA = B.ID_RUTA,
  A.ID_SUCURSAL = B.ID_SUCURSAL,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_BOLETO A USING
 (SELECT
  5 as ID_BOLETO,
  2 as ID_USUARIO,
  5 as ID_RUTA,
  3 as ID_SUCURSAL,
  555 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('22/04/2015 02:10:59.076000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  NULL as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_BOLETO = B.ID_BOLETO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_BOLETO, ID_USUARIO, ID_RUTA, ID_SUCURSAL, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_BOLETO, B.ID_USUARIO, B.ID_RUTA, B.ID_SUCURSAL, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_USUARIO = B.ID_USUARIO,
  A.ID_RUTA = B.ID_RUTA,
  A.ID_SUCURSAL = B.ID_SUCURSAL,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

COMMIT;
