SET DEFINE OFF;
MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  4 as ID_FLOTA,
  4 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'CVB-2560' as PLACA,
  '2007' as MODELO,
  38 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:17:27.718000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  5 as ID_FLOTA,
  4 as ID_TIPO_FLOTA,
  'AZUL' as COLOR,
  'LLDD-5410' as PLACA,
  '2009' as MODELO,
  40 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:18:18.963000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  6 as ID_FLOTA,
  2 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'AAS-0112' as PLACA,
  '2013' as MODELO,
  38 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:18:26.027000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  7 as ID_FLOTA,
  4 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'ASDF-2154' as PLACA,
  '2008' as MODELO,
  42 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:18:32.692000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  8 as ID_FLOTA,
  2 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'SSFE-2354' as PLACA,
  '2013' as MODELO,
  42 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:18:37.500000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  9 as ID_FLOTA,
  2 as ID_TIPO_FLOTA,
  'AZUL' as COLOR,
  'EFCS-2154' as PLACA,
  '2008' as MODELO,
  38 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:18:43.015000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  10 as ID_FLOTA,
  4 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'RFS-2145' as PLACA,
  '2013' as MODELO,
  40 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:18:47.878000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  11 as ID_FLOTA,
  4 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'ASTB-2356' as PLACA,
  '2008' as MODELO,
  40 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:18:56.739000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  12 as ID_FLOTA,
  3 as ID_TIPO_FLOTA,
  'AZUL' as COLOR,
  'TBGG-2354' as PLACA,
  '2008' as MODELO,
  44 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:20:05.042000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  13 as ID_FLOTA,
  3 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'GBRV-2365' as PLACA,
  '2013' as MODELO,
  40 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:20:13.349000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  14 as ID_FLOTA,
  4 as ID_TIPO_FLOTA,
  'AZUL' as COLOR,
  'TYBG-2589' as PLACA,
  '2008' as MODELO,
  40 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:20:30.843000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  15 as ID_FLOTA,
  2 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'TBG-2478' as PLACA,
  '2008' as MODELO,
  42 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:20:36.855000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  16 as ID_FLOTA,
  4 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'SWXX-3545' as PLACA,
  '2010' as MODELO,
  38 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:20:42.433000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  17 as ID_FLOTA,
  3 as ID_TIPO_FLOTA,
  'AZUL' as COLOR,
  'YHNH-2745' as PLACA,
  '2010' as MODELO,
  44 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:20:51.524000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  18 as ID_FLOTA,
  4 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'JUM-3125' as PLACA,
  '2010' as MODELO,
  42 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:21:19.604000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  19 as ID_FLOTA,
  2 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'IKHB-3454' as PLACA,
  '2013' as MODELO,
  43 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:21:20.849000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  20 as ID_FLOTA,
  3 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'AZZS-2233' as PLACA,
  '2010' as MODELO,
  40 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:21:25.100000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  21 as ID_FLOTA,
  4 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'FFRD-2333' as PLACA,
  '2010' as MODELO,
  38 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:21:26.126000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  22 as ID_FLOTA,
  3 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'VFRF-3455' as PLACA,
  '2009' as MODELO,
  40 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:21:27.313000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  23 as ID_FLOTA,
  2 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'GGTB-3556' as PLACA,
  '2014' as MODELO,
  44 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:21:28.953000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  24 as ID_FLOTA,
  4 as ID_TIPO_FLOTA,
  'AZUL' as COLOR,
  'DFBB-3658' as PLACA,
  '2010' as MODELO,
  42 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:21:31.118000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  25 as ID_FLOTA,
  3 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'FGHH-3669' as PLACA,
  '2008' as MODELO,
  40 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:21:32.454000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  26 as ID_FLOTA,
  4 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'YNHH-3677' as PLACA,
  '2013' as MODELO,
  38 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:21:34.173000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  27 as ID_FLOTA,
  3 as ID_TIPO_FLOTA,
  'AZUL' as COLOR,
  'UJMJ-3645' as PLACA,
  '2010' as MODELO,
  36 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:21:35.361000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  28 as ID_FLOTA,
  2 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'JJMM-3564' as PLACA,
  '2010' as MODELO,
  40 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:21:38.488000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  29 as ID_FLOTA,
  3 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'KKJH-2578' as PLACA,
  NULL as MODELO,
  41 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:21:42.762000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  30 as ID_FLOTA,
  4 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'JHGF-3544' as PLACA,
  NULL as MODELO,
  37 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:21:44.563000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  2 as ID_FLOTA,
  1 as ID_TIPO_FLOTA,
  'BLANCO' as COLOR,
  'VXCV-2488' as PLACA,
  '2005' as MODELO,
  42 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('20/04/2015 01:22:20.000000 AM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:20', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_FLOTA A USING
 (SELECT
  3 as ID_FLOTA,
  2 as ID_TIPO_FLOTA,
  'AZUL' as COLOR,
  'POP-565' as PLACA,
  '2008' as MODELO,
  40 as NRO_ASIENTOS,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('20/04/2015 01:23:00.899000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:22:59', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_FLOTA = B.ID_FLOTA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_FLOTA, ID_TIPO_FLOTA, COLOR, PLACA, MODELO, 
  NRO_ASIENTOS, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_FLOTA, B.ID_TIPO_FLOTA, B.COLOR, B.PLACA, B.MODELO, 
  B.NRO_ASIENTOS, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_TIPO_FLOTA = B.ID_TIPO_FLOTA,
  A.COLOR = B.COLOR,
  A.PLACA = B.PLACA,
  A.MODELO = B.MODELO,
  A.NRO_ASIENTOS = B.NRO_ASIENTOS,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

COMMIT;
