SET DEFINE OFF;
MERGE INTO UAB_GET.T_USUARIO A USING
 (SELECT
  2 as ID_USUARIO,
  1 as ID_PERSONA,
  3 as ID_SUCURSAL,
  1 as ID_TIPO_USUARIO,
  '123' as CLAVE,
  'juanes' as USUARIO,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('20/04/2015 01:44:40.423000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:44:39', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_USUARIO = B.ID_USUARIO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_USUARIO, ID_PERSONA, ID_SUCURSAL, ID_TIPO_USUARIO, CLAVE, 
  USUARIO, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_USUARIO, B.ID_PERSONA, B.ID_SUCURSAL, B.ID_TIPO_USUARIO, B.CLAVE, 
  B.USUARIO, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_PERSONA = B.ID_PERSONA,
  A.ID_SUCURSAL = B.ID_SUCURSAL,
  A.ID_TIPO_USUARIO = B.ID_TIPO_USUARIO,
  A.CLAVE = B.CLAVE,
  A.USUARIO = B.USUARIO,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.T_USUARIO A USING
 (SELECT
  3 as ID_USUARIO,
  2 as ID_PERSONA,
  2 as ID_SUCURSAL,
  3 as ID_TIPO_USUARIO,
  '321' as CLAVE,
  'sony' as USUARIO,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('20/04/2015 01:45:22.039000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:45:21', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_USUARIO = B.ID_USUARIO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_USUARIO, ID_PERSONA, ID_SUCURSAL, ID_TIPO_USUARIO, CLAVE, 
  USUARIO, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, AUD_FECHA, 
  FECHA_REGISTRO)
VALUES (
  B.ID_USUARIO, B.ID_PERSONA, B.ID_SUCURSAL, B.ID_TIPO_USUARIO, B.CLAVE, 
  B.USUARIO, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, 
  B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.ID_PERSONA = B.ID_PERSONA,
  A.ID_SUCURSAL = B.ID_SUCURSAL,
  A.ID_TIPO_USUARIO = B.ID_TIPO_USUARIO,
  A.CLAVE = B.CLAVE,
  A.USUARIO = B.USUARIO,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

COMMIT;
