SET DEFINE OFF;
MERGE INTO UAB_GET.TPAR_SUCURSAL A USING
 (SELECT
  5 as ID_SUCURSAL,
  'COCHABAMBA' as NOMBRE,
  '2445556' as TELEFONO,
  'SN' as DIRECCION,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:43:55.053000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:41:19', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_SUCURSAL = B.ID_SUCURSAL)
WHEN NOT MATCHED THEN 
INSERT (
  ID_SUCURSAL, NOMBRE, TELEFONO, DIRECCION, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_SUCURSAL, B.NOMBRE, B.TELEFONO, B.DIRECCION, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.NOMBRE = B.NOMBRE,
  A.TELEFONO = B.TELEFONO,
  A.DIRECCION = B.DIRECCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.TPAR_SUCURSAL A USING
 (SELECT
  6 as ID_SUCURSAL,
  'SANTA CRUZ' as NOMBRE,
  '24544447' as TELEFONO,
  'SN' as DIRECCION,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:44:18.702000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:41:19', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_SUCURSAL = B.ID_SUCURSAL)
WHEN NOT MATCHED THEN 
INSERT (
  ID_SUCURSAL, NOMBRE, TELEFONO, DIRECCION, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_SUCURSAL, B.NOMBRE, B.TELEFONO, B.DIRECCION, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.NOMBRE = B.NOMBRE,
  A.TELEFONO = B.TELEFONO,
  A.DIRECCION = B.DIRECCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.TPAR_SUCURSAL A USING
 (SELECT
  7 as ID_SUCURSAL,
  'TARIJITA' as NOMBRE,
  '2445665' as TELEFONO,
  'SN' as DIRECCION,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:44:26.619000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:41:19', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_SUCURSAL = B.ID_SUCURSAL)
WHEN NOT MATCHED THEN 
INSERT (
  ID_SUCURSAL, NOMBRE, TELEFONO, DIRECCION, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_SUCURSAL, B.NOMBRE, B.TELEFONO, B.DIRECCION, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.NOMBRE = B.NOMBRE,
  A.TELEFONO = B.TELEFONO,
  A.DIRECCION = B.DIRECCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.TPAR_SUCURSAL A USING
 (SELECT
  8 as ID_SUCURSAL,
  'ORURITO' as NOMBRE,
  '2114569' as TELEFONO,
  'SN' as DIRECCION,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:44:36.727000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:41:19', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_SUCURSAL = B.ID_SUCURSAL)
WHEN NOT MATCHED THEN 
INSERT (
  ID_SUCURSAL, NOMBRE, TELEFONO, DIRECCION, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_SUCURSAL, B.NOMBRE, B.TELEFONO, B.DIRECCION, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.NOMBRE = B.NOMBRE,
  A.TELEFONO = B.TELEFONO,
  A.DIRECCION = B.DIRECCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.TPAR_SUCURSAL A USING
 (SELECT
  9 as ID_SUCURSAL,
  'TUPIZA' as NOMBRE,
  '2445697' as TELEFONO,
  'SN' as DIRECCION,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:44:44.083000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:41:19', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_SUCURSAL = B.ID_SUCURSAL)
WHEN NOT MATCHED THEN 
INSERT (
  ID_SUCURSAL, NOMBRE, TELEFONO, DIRECCION, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_SUCURSAL, B.NOMBRE, B.TELEFONO, B.DIRECCION, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.NOMBRE = B.NOMBRE,
  A.TELEFONO = B.TELEFONO,
  A.DIRECCION = B.DIRECCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.TPAR_SUCURSAL A USING
 (SELECT
  10 as ID_SUCURSAL,
  'TRINIDAD' as NOMBRE,
  '2546887' as TELEFONO,
  'SN' as DIRECCION,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:44:51.015000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:41:19', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_SUCURSAL = B.ID_SUCURSAL)
WHEN NOT MATCHED THEN 
INSERT (
  ID_SUCURSAL, NOMBRE, TELEFONO, DIRECCION, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_SUCURSAL, B.NOMBRE, B.TELEFONO, B.DIRECCION, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.NOMBRE = B.NOMBRE,
  A.TELEFONO = B.TELEFONO,
  A.DIRECCION = B.DIRECCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.TPAR_SUCURSAL A USING
 (SELECT
  11 as ID_SUCURSAL,
  'COBIJA' as NOMBRE,
  '2366355' as TELEFONO,
  'SN' as DIRECCION,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:44:54.238000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:41:19', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_SUCURSAL = B.ID_SUCURSAL)
WHEN NOT MATCHED THEN 
INSERT (
  ID_SUCURSAL, NOMBRE, TELEFONO, DIRECCION, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_SUCURSAL, B.NOMBRE, B.TELEFONO, B.DIRECCION, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.NOMBRE = B.NOMBRE,
  A.TELEFONO = B.TELEFONO,
  A.DIRECCION = B.DIRECCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.TPAR_SUCURSAL A USING
 (SELECT
  12 as ID_SUCURSAL,
  'SUCRE' as NOMBRE,
  '2445874' as TELEFONO,
  'SN' as DIRECCION,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('28/04/2015 02:45:34.299000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:41:19', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_SUCURSAL = B.ID_SUCURSAL)
WHEN NOT MATCHED THEN 
INSERT (
  ID_SUCURSAL, NOMBRE, TELEFONO, DIRECCION, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_SUCURSAL, B.NOMBRE, B.TELEFONO, B.DIRECCION, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.NOMBRE = B.NOMBRE,
  A.TELEFONO = B.TELEFONO,
  A.DIRECCION = B.DIRECCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.TPAR_SUCURSAL A USING
 (SELECT
  2 as ID_SUCURSAL,
  'QUILLACOLLO' as NOMBRE,
  '2421212' as TELEFONO,
  'AV LAS AMERICAS N 256' as DIRECCION,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('20/04/2015 01:39:35.000000 AM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:39:35', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_SUCURSAL = B.ID_SUCURSAL)
WHEN NOT MATCHED THEN 
INSERT (
  ID_SUCURSAL, NOMBRE, TELEFONO, DIRECCION, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_SUCURSAL, B.NOMBRE, B.TELEFONO, B.DIRECCION, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.NOMBRE = B.NOMBRE,
  A.TELEFONO = B.TELEFONO,
  A.DIRECCION = B.DIRECCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.TPAR_SUCURSAL A USING
 (SELECT
  3 as ID_SUCURSAL,
  'EL ALTO' as NOMBRE,
  '2734550' as TELEFONO,
  'VILLA DOLORES N 236' as DIRECCION,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('20/04/2015 01:40:27.145000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:40:25', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_SUCURSAL = B.ID_SUCURSAL)
WHEN NOT MATCHED THEN 
INSERT (
  ID_SUCURSAL, NOMBRE, TELEFONO, DIRECCION, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_SUCURSAL, B.NOMBRE, B.TELEFONO, B.DIRECCION, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.NOMBRE = B.NOMBRE,
  A.TELEFONO = B.TELEFONO,
  A.DIRECCION = B.DIRECCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

MERGE INTO UAB_GET.TPAR_SUCURSAL A USING
 (SELECT
  4 as ID_SUCURSAL,
  'LA PAZ' as NOMBRE,
  '2256542' as TELEFONO,
  'AV MONTES N 548' as DIRECCION,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('20/04/2015 01:41:20.877000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/20/2015 01:41:19', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGISTRO
  FROM DUAL) B
ON (A.ID_SUCURSAL = B.ID_SUCURSAL)
WHEN NOT MATCHED THEN 
INSERT (
  ID_SUCURSAL, NOMBRE, TELEFONO, DIRECCION, APP_ID_USUARIO, 
  AUD_ESTADO, AUD_USUARIO, AUD_FECHA, FECHA_REGISTRO)
VALUES (
  B.ID_SUCURSAL, B.NOMBRE, B.TELEFONO, B.DIRECCION, B.APP_ID_USUARIO, 
  B.AUD_ESTADO, B.AUD_USUARIO, B.AUD_FECHA, B.FECHA_REGISTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.NOMBRE = B.NOMBRE,
  A.TELEFONO = B.TELEFONO,
  A.DIRECCION = B.DIRECCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGISTRO = B.FECHA_REGISTRO;

COMMIT;
