SET DEFINE OFF;
MERGE INTO UAB_GET.TPAR_TIPO_PERSONA A USING
 (SELECT
  1 as ID_TIPO_PERSONA,
  'EMPLEADO' as DESCRIPCION,
  12 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('02/04/2015 01:50:54.084000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/01/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGSTRO
  FROM DUAL) B
ON (A.ID_TIPO_PERSONA = B.ID_TIPO_PERSONA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_TIPO_PERSONA, DESCRIPCION, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, 
  AUD_FECHA, FECHA_REGSTRO)
VALUES (
  B.ID_TIPO_PERSONA, B.DESCRIPCION, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, 
  B.AUD_FECHA, B.FECHA_REGSTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPCION = B.DESCRIPCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGSTRO = B.FECHA_REGSTRO;

MERGE INTO UAB_GET.TPAR_TIPO_PERSONA A USING
 (SELECT
  2 as ID_TIPO_PERSONA,
  'CLIENTE' as DESCRIPCION,
  13 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('02/04/2015 01:51:29.003000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA,
  TO_DATE('04/02/2015 01:51:26', 'MM/DD/YYYY HH24:MI:SS') as FECHA_REGSTRO
  FROM DUAL) B
ON (A.ID_TIPO_PERSONA = B.ID_TIPO_PERSONA)
WHEN NOT MATCHED THEN 
INSERT (
  ID_TIPO_PERSONA, DESCRIPCION, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, 
  AUD_FECHA, FECHA_REGSTRO)
VALUES (
  B.ID_TIPO_PERSONA, B.DESCRIPCION, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, 
  B.AUD_FECHA, B.FECHA_REGSTRO)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPCION = B.DESCRIPCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA,
  A.FECHA_REGSTRO = B.FECHA_REGSTRO;

COMMIT;
