SET DEFINE OFF;
MERGE INTO UAB_GET.TPAR_TIPO_ASIENTO A USING
 (SELECT
  1 as ID_TIPO_ASIENTO,
  'PASILLO' as DESCRIPCION,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('20/04/2015 02:14:53.000000 AM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA
  FROM DUAL) B
ON (A.ID_TIPO_ASIENTO = B.ID_TIPO_ASIENTO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_TIPO_ASIENTO, DESCRIPCION, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, 
  AUD_FECHA)
VALUES (
  B.ID_TIPO_ASIENTO, B.DESCRIPCION, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, 
  B.AUD_FECHA)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPCION = B.DESCRIPCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA;

MERGE INTO UAB_GET.TPAR_TIPO_ASIENTO A USING
 (SELECT
  2 as ID_TIPO_ASIENTO,
  'VENTANA' as DESCRIPCION,
  500 as APP_ID_USUARIO,
  1 as AUD_ESTADO,
  'SYSTEM' as AUD_USUARIO,
  TO_TIMESTAMP('20/04/2015 02:15:11.000000 PM','DD/MM/YYYY HH12:MI:SS.FF AM') as AUD_FECHA
  FROM DUAL) B
ON (A.ID_TIPO_ASIENTO = B.ID_TIPO_ASIENTO)
WHEN NOT MATCHED THEN 
INSERT (
  ID_TIPO_ASIENTO, DESCRIPCION, APP_ID_USUARIO, AUD_ESTADO, AUD_USUARIO, 
  AUD_FECHA)
VALUES (
  B.ID_TIPO_ASIENTO, B.DESCRIPCION, B.APP_ID_USUARIO, B.AUD_ESTADO, B.AUD_USUARIO, 
  B.AUD_FECHA)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPCION = B.DESCRIPCION,
  A.APP_ID_USUARIO = B.APP_ID_USUARIO,
  A.AUD_ESTADO = B.AUD_ESTADO,
  A.AUD_USUARIO = B.AUD_USUARIO,
  A.AUD_FECHA = B.AUD_FECHA;

COMMIT;
